# Configuración del plugin Servidirectorios

database:
  # Tipo de almacenamiento: 'h2' o 'mysql'
  type: 'h2'
  # Archivo para la base de datos H2 (relativo a la carpeta de datos del plugin)
  file: 'database'
  mysql:
    host: 'localhost'
    port: '3306'
    database: 'servidirectorios_db'
    username: 'usuario'
    password: 'contraseña'

credit-slots-stay-on-page-switch: true

# Rango de puestos
credit-slots:
  start: 0
  end: 8

servidolar-slots:
  start: 9
  end: 25

# Precios de los puestos
slot-prices:
  # Créditos
  '0': 1.25
  '1': 1.1
  '2': 1.1
  '3': 1.1
  '4': 1.1
  '5': 1.1
  '6': 1.1
  '7': 1.1
  '8': 1.1

  # Servidólares - Página 1
  '9': 7000.0
  '10': 7000.0
  '11': 7000.0
  '12': 7000.0
  '13': 7000.0
  '14': 7000.0
  '15': 7000.0
  '16': 7000.0
  '17': 7000.0
  '18': 7000.0
  '19': 7000.0
  '20': 7000.0
  '21': 7000.0
  '22': 7000.0
  '23': 7000.0
  '24': 7000.0
  '25': 7000.0
# Servidólares - Página 2
  '26': 2500.0
  '27': 2500.0
  '28': 2500.0
  '29': 2500.0
  '30': 2500.0
  '31': 2500.0
  '32': 2500.0
  '33': 2500.0
  '34': 2500.0
  '35': 2500.0
  '36': 2500.0
  '37': 2500.0
  '38': 2500.0
  '39': 2500.0
  '40': 2500.0
  '41': 2500.0
  '42': 2500.0

