name: Servidirectorios
main: org.servicraft.servidirectorios.Servidirectorios
version: "1.0.0"
api-version: 1.21.3
commands:
    directorios:
      description: Abre el menú principal de directorios (atajos y tiendas).
      usage: /directorios [tiendas]
    createshortcut:
      description: Crea un nuevo atajo en tu ubicación actual.
      usage: /createshortcut <nombre> <descripcion>
    servidirectorios:
      description: Comandos administrativos de Servidirectorios
      usage: /servidirectorios admin
permissions:
  servidirectorios.admin:
    description: Permite eliminar puestos y reembolsar al propietario
    default: op
